ds <- read.table("household_power_consumption.txt", sep=";", header=TRUE, skip=66636, nrow=2880, stringsAsFactor=FALSE, col.names=c("Date","Time","Global_active_power","Global_reactive_power","Voltage","Global_intensity","Sub_metering_1","Sub_metering_2","Sub_metering_3"))
ds$Time <- strptime(paste(ds$Date,ds$Time), "%d/%m/%Y %H:%M:%S")
png("plot2.png", width=480, height=480)
plot (ds$Time, ds$Global_active_power, type="l", xlab="", ylab="Global Active Power (kilowatts)")
dev.off()